// Auto-generated by tools/gen-status. Do not edit.
// Run: cargo run -p gen-status

pub fn generated_status() -> &'static [(&'static str, u32, bool, bool)] {
    &[
        ("sw-cor24-emulator", 1, false, false),
        ("sw-cor24-x-assembler", 0, false, false),
        ("sw-cor24-assembler", 0, false, true),
        ("sw-cor24-project", 0, true, true),
        ("sw-cor24-x-tinyc", 18, true, true),
        ("sw-cor24-rust", 0, false, false),
        ("sw-cor24-pcode", 0, true, true),
        ("sw-cor24-x-pc-aotc", 0, true, true),
        ("sw-cor24-pascal", 0, false, false),
        ("sw-cor24-macrolisp", 0, false, false),
        ("sw-cor24-forth", 0, false, false),
        ("sw-cor24-apl", 0, true, true),
        ("sw-cor24-basic", 0, false, true),
        ("sw-cor24-fortran", 0, false, false),
        ("sw-cor24-plsw", 0, true, true),
        ("sw-cor24-script", 0, true, true),
        ("sw-cor24-monitor", 0, true, true),
        ("sw-cor24-debugger", 0, false, false),
        ("web-sw-cor24-assembler", 0, false, false),
        ("web-sw-cor24-pcode", 0, true, true),
        ("web-sw-cor24-tinyc", 0, false, false),
        ("web-sw-cor24-macrolisp", 0, false, false),
        ("web-sw-cor24-pascal", 0, false, false),
        ("web-sw-cor24-apl", 0, true, true),
        ("web-sw-cor24-forth", 0, false, false),
        ("web-sw-cor24-plsw", 0, false, false),
        ("web-sw-cor24-rust", 0, false, false),
        ("web-sw-cor24-demos", 0, true, true),
    ]
}
