use std::collections::BTreeMap;
use std::fmt::Write;
use std::path::PathBuf;
use std::process::Command;

const DEFAULT_ORG: &str = "sw-embed";

// (repo, group, org_override). org_override = None means DEFAULT_ORG.
const REPOS: &[(&str, &str, Option<&str>)] = &[
    ("sw-cor24-assembler", "Foundation", None),
    ("sw-cor24-emulator", "Foundation", None),
    ("sw-cor24-project", "Foundation", None),
    ("sw-cor24-x-assembler", "Foundation", None),
    ("sw-cor24-rust", "Cross-compilers", None),
    ("sw-cor24-x-tinyc", "Cross-compilers", None),
    ("sw-cor24-pascal", "P-code", None),
    ("sw-cor24-pcode", "P-code", None),
    ("sw-cor24-x-pc-aotc", "P-code", None),
    ("sw-cor24-apl", "Native langs", None),
    ("sw-cor24-basic", "Native langs", None),
    ("sw-cor24-forth", "Native langs", None),
    ("sw-cor24-fortran", "Native langs", None),
    ("sw-cor24-macrolisp", "Native langs", None),
    ("sw-cor24-plsw", "Native langs", None),
    ("sw-cor24-smalltalk", "Native langs", None),
    ("sw-cor24-snobol4", "Native langs", None),
    ("sw-cor24-script", "Native langs", None),
    ("tuplet", "Native langs", Some("sw-vibe-coding")),
    ("sw-cor24-debugger", "System", None),
    ("sw-cor24-monitor", "System", None),
    ("sw-cor24-yocto-ed", "System", None),
    ("web-sw-cor24-apl", "Web UIs", None),
    ("web-sw-cor24-assembler", "Web UIs", None),
    ("web-sw-cor24-demos", "Web UIs", None),
    ("web-sw-cor24-forth", "Web UIs", None),
    ("web-sw-cor24-macrolisp", "Web UIs", None),
    ("web-sw-cor24-pascal", "Web UIs", None),
    ("web-sw-cor24-pcode", "Web UIs", None),
    ("web-sw-cor24-plsw", "Web UIs", None),
    ("web-sw-cor24-smalltalk", "Web UIs", None),
    ("web-sw-cor24-snobol4", "Web UIs", None),
    ("web-sw-cor24-rust", "Web UIs", None),
    ("web-sw-cor24-tinyc", "Web UIs", None),
];

struct Row {
    issues: u32,
    has_plan: bool,
    has_steps: bool,
}

fn main() {
    let mut rows: BTreeMap<&str, Row> = BTreeMap::new();

    for &(repo, _group, org_override) in REPOS {
        let org = org_override.unwrap_or(DEFAULT_ORG);
        eprint!("  {org}/{repo}... ");
        let issues = fetch_issues(org, repo);
        let has_plan = path_exists(org, repo, ".agentrail/plan.md");
        let has_steps = path_exists(org, repo, ".agentrail/steps");
        eprintln!("issues={issues} plan={has_plan} steps={has_steps}");
        rows.insert(
            repo,
            Row {
                issues,
                has_plan,
                has_steps,
            },
        );
    }

    let out = generate(&rows);
    let project_root = find_project_root();
    let dest = project_root.join("src/data/status/generated.rs");
    std::fs::write(&dest, &out).expect("failed to write output");
    println!("Generated {}", dest.display());
}

fn gh(args: &[&str]) -> String {
    let mut cmd = Command::new("gh");
    cmd.args(args);
    let output = cmd.output().expect("failed to run gh");
    String::from_utf8_lossy(&output.stdout).trim().to_string()
}

fn fetch_issues(org: &str, repo: &str) -> u32 {
    let out = gh(&[
        "api",
        &format!("repos/{org}/{repo}/issues?state=open&per_page=100"),
        "--jq",
        "length",
    ]);
    out.parse().unwrap_or(0)
}

fn path_exists(org: &str, repo: &str, path: &str) -> bool {
    gh_exit_code(&format!("repos/{org}/{repo}/contents/{path}")) == 0
}

fn gh_exit_code(path: &str) -> i32 {
    let mut cmd = Command::new("gh");
    cmd.args(["api", path]);
    cmd.stdout(std::process::Stdio::null());
    cmd.stderr(std::process::Stdio::null());
    cmd.status().map(|s| s.code().unwrap_or(1)).unwrap_or(1)
}

fn generate(rows: &BTreeMap<&str, Row>) -> String {
    let mut out = String::new();
    writeln!(out, "// Auto-generated by tools/gen-status. Do not edit.").unwrap();
    writeln!(out, "// Run: cargo run -p gen-status").unwrap();
    writeln!(out).unwrap();
    writeln!(
        out,
        "pub fn generated_status() -> &'static [(&'static str, u32, bool, bool)] {{"
    )
    .unwrap();
    writeln!(out, "    &[",).unwrap();
    for &(repo, _group, _org) in REPOS {
        let row = &rows[repo];
        writeln!(
            out,
            "        (\"{repo}\", {}, {}, {}),",
            row.issues, row.has_plan, row.has_steps,
        )
        .unwrap();
    }
    writeln!(out, "    ]").unwrap();
    writeln!(out, "}}").unwrap();
    out
}

fn find_project_root() -> PathBuf {
    let mut dir = std::env::current_dir().expect("no cwd");
    loop {
        if dir.join("src/data/isa").exists() {
            return dir;
        }
        if !dir.pop() {
            return dir;
        }
    }
}
