#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT="$PROJECT_DIR/src/data/status_generated.rs"

REPOS=(
    sw-cor24-emulator:Foundation
    sw-cor24-x-assembler:Foundation
    sw-cor24-assembler:Foundation
    sw-cor24-project:Foundation
    sw-cor24-x-tinyc:Cross-compilers
    sw-cor24-rust:Cross-compilers
    sw-cor24-pcode:P-code
    sw-cor24-x-pc-aotc:P-code
    sw-cor24-pascal:P-code
    sw-cor24-macrolisp:Native-langs
    sw-cor24-forth:Native-langs
    sw-cor24-apl:Native-langs
    sw-cor24-basic:Native-langs
    sw-cor24-fortran:Native-langs
    sw-cor24-plsw:Native-langs
    sw-cor24-smalltalk:Native-langs
    sw-cor24-script:Native-langs
    sw-cor24-monitor:System
    sw-cor24-debugger:System
    sw-cor24-yocto-ed:System
    web-sw-cor24-assembler:Web-UIs
    web-sw-cor24-pcode:Web-UIs
    web-sw-cor24-tinyc:Web-UIs
    web-sw-cor24-macrolisp:Web-UIs
    web-sw-cor24-pascal:Web-UIs
    web-sw-cor24-apl:Web-UIs
    web-sw-cor24-forth:Web-UIs
    web-sw-cor24-plsw:Web-UIs
    web-sw-cor24-smalltalk:Web-UIs
    web-sw-cor24-rust:Web-UIs
    web-sw-cor24-demos:Web-UIs
)

{
echo "// Auto-generated by scripts/gen-status.sh. Do not edit."
echo "// Run: ./scripts/gen-status.sh"
echo ""
echo "pub fn issue_counts() -> &'static [(&'static str, u32)] {"
echo "    &["
for entry in "${REPOS[@]}"; do
    repo="${entry%%:*}"
    group="${entry##*:}"
    count=$(gh api "repos/sw-embed/$repo/issues?state=open&per_page=100" --jq 'length' 2>/dev/null || echo "0")
    if ! [[ "$count" =~ ^[0-9]+$ ]]; then
        count="0"
    fi
    echo "        (\"$repo\", $count),"
done
echo "    ]"
echo "}"
} > "$OUTPUT"
