// Auto-generated by scripts/gen-status.sh. Do not edit.
// Run: ./scripts/gen-status.sh

pub fn issue_counts() -> &'static [(&'static str, u32)] {
    &[
        ("sw-cor24-emulator", 1),
        ("sw-cor24-x-assembler", 0),
        ("sw-cor24-assembler", 0),
        ("sw-cor24-project", 0),
        ("sw-cor24-x-tinyc", 14),
        ("sw-cor24-rust", 0),
        ("sw-cor24-pcode", 0),
        ("sw-cor24-x-pc-aotc", 0),
        ("sw-cor24-pascal", 0),
        ("sw-cor24-macrolisp", 0),
        ("sw-cor24-forth", 0),
        ("sw-cor24-apl", 0),
        ("sw-cor24-basic", 0),
        ("sw-cor24-fortran", 0),
        ("sw-cor24-plsw", 0),
        ("sw-cor24-smalltalk", 0),
        ("sw-cor24-script", 0),
        ("sw-cor24-monitor", 0),
        ("sw-cor24-debugger", 0),
        ("web-sw-cor24-assembler", 0),
        ("web-sw-cor24-pcode", 0),
        ("web-sw-cor24-tinyc", 0),
        ("web-sw-cor24-macrolisp", 0),
        ("web-sw-cor24-pascal", 0),
        ("web-sw-cor24-apl", 1),
        ("web-sw-cor24-forth", 0),
        ("web-sw-cor24-plsw", 0),
        ("web-sw-cor24-smalltalk", 0),
        ("web-sw-cor24-rust", 0),
        ("web-sw-cor24-demos", 0),
    ]
}
